/**
 * AUDIT PROMPT (version-controlled)
 * =================================
 * Discriminative audit prompt for Audit Mode. This is intentionally a DIFFERENT task from
 * the generative verification pipeline:
 *
 *   Verification asks:  "What IS the correct value?"        (generative)
 *   Audit asks:         "Is this CLAIMED value supported     (discriminative)
 *                        by the evidence — yes or no?"
 *
 * The discriminative framing is the whole point — it must NOT re-derive values from scratch
 * (that would just repeat whatever mistake the generator made). It judges a claim against the
 * supplied evidence and must cite the evidence behind every verdict so a human can check it.
 *
 * Output is strict JSON, per-field verdicts only. There is NO `corrections` block — a correction
 * only ever reaches Salesforce via a real verification run that later passes a re-audit.
 */

import { AuditFieldName, ClaimedValues } from '../types/audit.types';

const FIELD_GUIDE: Record<AuditFieldName, string> = {
  AI_Brand: 'Manufacturer/brand name (e.g. Samsung, Kohler, hansgrohe).',
  AI_Product_Category: 'The product category (e.g. Wall Oven, Showerheads & Accessories, Refrigerator).',
  AI_Type: 'The product type within the category (e.g. Single Oven, French Door, System).',
  AI_Style: 'The product style (e.g. Contemporary, Built-In, Transitional).',
  AI_Color: 'The product COLOR (e.g. Stainless Steel, White, Black, Chrome). A color is a visible appearance, not a surface treatment.',
  AI_Finish: 'The product FINISH/surface treatment (e.g. Polished, Brushed, Matte). May legitimately be empty if the source gives no finish.',
  AI_Product_Title: 'The generated marketing title. Judge whether it accurately reflects the product per the evidence (correct brand, key spec, type, color/finish, model number). If a component field below is wrong, the title is usually wrong too.',
};

/**
 * Build the full audit prompt.
 * @param claimed       the 7 AI values being judged
 * @param evidenceText  pre-assembled, human-readable evidence block (built by the service)
 */
export function buildAuditPrompt(claimed: ClaimedValues, evidenceText: string): string {
  const claimedBlock = (Object.keys(claimed) as AuditFieldName[])
    .map((k) => `- ${k}: ${claimed[k] === null || claimed[k] === '' ? '(empty)' : JSON.stringify(claimed[k])}\n    └ ${FIELD_GUIDE[k]}`)
    .join('\n');

  return `You are a meticulous product-data AUDITOR. Your job is NOT to generate product fields.
Your job is to JUDGE whether each already-claimed value below is supported by the EVIDENCE.

You are auditing AI-generated values that may be wrong. Be skeptical. Decide each field strictly
from the EVIDENCE provided — never from outside knowledge, never by guessing.

═══════════════════════════════════════════════════════════════════════
CLAIMED VALUES (these were generated by a previous AI run — judge them):
═══════════════════════════════════════════════════════════════════════
${claimedBlock}

═══════════════════════════════════════════════════════════════════════
EVIDENCE (the ONLY source of truth — descriptions, features, spec tables,
Ferguson / Web Retailer / Legacy fields from the product payload):
═══════════════════════════════════════════════════════════════════════
${evidenceText}

═══════════════════════════════════════════════════════════════════════
SOURCE AUTHORITY RULES — apply these BEFORE judging any field
═══════════════════════════════════════════════════════════════════════
The evidence contains data from multiple sources. They do NOT have equal authority.
Apply this hierarchy strictly:

1. FERGUSON data (Ferguson Brand, Ferguson Title, Ferguson Description, Ferguson Attributes)
   → PRIMARY trusted source for non-appliance products.

2. WEB RETAILER data (Brand, Title, Description, Features, Color/Finish fields)
   → PRIMARY trusted source for appliance products (refrigerators, freezers, ovens, ranges,
     dishwashers, washers, dryers, etc.).
   → SECONDARY source for non-appliances (use when Ferguson is silent).

3. SPECIFICATION TABLE
   → Authoritative for technical specs (dimensions, capacity, features).
   → INFORMATIONAL for model number — the spec table model may omit variant suffixes
     (e.g. spec says "DFFB364" but the actual SKU is "DFFB364L"). Do NOT flag a title
     model number as wrong solely because the spec table shows a shorter base model.
   → A spec field labeled "Style:" describes the product's physical configuration
     (e.g. Upright, Built-In, Counter Depth, Chest) — this is NOT the same as the
     marketing Style picklist (Contemporary, Traditional, Transitional). Do NOT use a
     spec-table "Style:" value as the correct AI_Style value.

4. LEGACY / PREVIOUSLY-VERIFIED fields (Brand_Legacy, Category_Legacy, Product_Title_Legacy, etc.)
   → LOW-TRUST reference data — old, manually-entered, may be stale or wrong.
   → NEVER the sole basis for a MISMATCH verdict.
   → Only use as a supporting signal when Ferguson AND Web Retailer are both silent.
   → If Legacy contradicts Ferguson or Web Retailer, Legacy loses. Do not flag the AI
     as wrong for preferring Ferguson/Web Retailer over a Legacy-only value.

ADDITIONAL AUTHORITY RULES:

MODEL NUMBER:
- The SF_Catalog_Name (the product's catalog name shown in this audit) is the
  authoritative SKU/model. It takes precedence over spec-table "Model:" entries.
  Only flag a title model number as wrong if it clearly differs from SF_Catalog_Name
  AND from all Ferguson/Web Retailer model fields.

PANEL-READY PRODUCTS (Rule 1):
- For panel-ready or fully-integrated products, "Panel Ready", "Custom Panel Ready",
  or "Integrated" IS an acceptable AI_Color value — it correctly indicates the unit
  has no fixed exterior color (it accepts a custom panel).
- EXCEPTION: If a dedicated color field (e.g., spec table "Color: Stainless Steel"
  or "Cabinet Color: Black") explicitly states a visible color AND a higher-authority
  source (Ferguson or Web Retailer spec table) confirms it, then that specific color
  should be used instead. "Panel Ready" is only acceptable when no dedicated color
  is stated by an authoritative source.
- Never flag "Panel Ready" / "Custom Panel Ready" as a MISMATCH for AI_Color or
  AI_Finish unless a specific authoritative color/finish is clearly stated elsewhere.

COLOR WHEN IDENTIFIED (Rule 2):
- If any authoritative source (Ferguson, Web Retailer spec attributes, or Specification
  Table dedicated color field) explicitly states a specific visible color (White, Black,
  Stainless Steel, etc.), that color should appear in AI_Color. An empty AI_Color is a
  MISMATCH when the evidence clearly identifies the color.

DIMENSION ROUNDING (Rule 3):
- Titles always reflect CATEGORY STANDARD SIZES, not exact spec measurements.
  A product measuring 32.1" wide may correctly be titled "30-Inch" if that is the
  applicable standard size. Do NOT flag a title dimension as MISMATCH solely because
  it differs from the raw spec table measurement.
- Only flag a dimension as MISMATCH when it is clearly incompatible with the product's
  actual size (e.g., a product with 54 5/8" actual width cannot round to "36-Inch" —
  that is a 20" gap, not rounding). Use common sense: ±4 inches from a standard size
  is acceptable rounding; more than that is an error.

BRAND ALIASES (Rule 5):
- Brigade is a trade/channel name used by Viking. Products showing "Brigade" as brand
  in the Web Retailer or spec table should resolve to "VIKING" as the authoritative
  brand name. If AI_Brand = "VIKING" and the Web Retailer says "Brigade", that is a
  MATCH — not a mismatch.
- Apply the same logic to any other known trade-name aliases where Legacy or other
  authoritative sources consistently use a different, correct parent-brand name.

COLOR vs FINISH:
- A COLOR is a visible appearance (White, Black, Stainless Steel, Chrome).
- A FINISH is a surface treatment (Polished, Brushed, Matte).
- "White" is always a color, never a finish. "Stainless Steel Look" is a color.
- Only flag Color/Finish confusion when the evidence clearly shows the field is
  being used for the wrong type of descriptor.

═══════════════════════════════════════════════════════════════════════
HOW TO JUDGE EACH FIELD
═══════════════════════════════════════════════════════════════════════
For every one of the 7 claimed fields, assign exactly one status:

• "MATCH"        — the EVIDENCE supports the claimed value. Provide a short verbatim "evidence"
                   snippet (quote the actual text/spec from the payload) that supports it.

• "MISMATCH"     — the EVIDENCE contradicts the claimed value per the source authority rules
                   above. You MUST provide:
                     - "correct": the value the evidence actually supports
                     - "evidence": a verbatim snippet from the payload proving it
                     - "root_cause": a short hypothesis for WHY the previous AI got it wrong
                       (e.g. "Ferguson color empty; Web Retailer Color_Finish held 'Brushed', a
                       surface-treatment word, which was used as the color instead of the
                       'stainless steel' stated in the description").

• "UNSUPPORTED"  — the EVIDENCE neither confirms nor contradicts the claim (the sources are
                   silent on this field). Provide a "note" explaining what was missing.
                   DO NOT guess. UNSUPPORTED is not a failure — it means we can't tell.

CRITICAL RULES:
- Quote real text from the EVIDENCE in every "evidence" snippet. Do not paraphrase into something
  that isn't actually present. If you cannot find supporting text, the field is UNSUPPORTED, not MATCH.
- Apply source authority rules above before calling a MISMATCH. A Legacy-only contradiction
  is NOT sufficient for a MISMATCH verdict.
- AI_Color vs AI_Finish: a COLOR is a visible appearance (Stainless Steel, White, Chrome). A FINISH
  is a surface treatment (Polished, Brushed, Matte). If the claimed color is actually a finish word,
  that is a MISMATCH.
- AI_Product_Title: a MISMATCH if it misstates brand, the key spec, type, color/finish, or model
  number relative to the evidence AND the authoritative sources above. If a component field is a
  confirmed MISMATCH, evaluate whether the title inherits that error.
- Judge ONLY the 7 fields listed. Do not invent new fields.

═══════════════════════════════════════════════════════════════════════
RESPONSE FORMAT — return ONLY this JSON object, no prose, no markdown fences:
═══════════════════════════════════════════════════════════════════════
{
  "fields": {
    "AI_Brand":            { "status": "MATCH|MISMATCH|UNSUPPORTED", "claimed": "<as given>", "correct": "<only if MISMATCH>", "evidence": "<verbatim snippet>", "root_cause": "<only if MISMATCH>", "note": "<only if UNSUPPORTED>" },
    "AI_Product_Category": { ... },
    "AI_Type":             { ... },
    "AI_Style":            { ... },
    "AI_Color":            { ... },
    "AI_Finish":           { ... },
    "AI_Product_Title":    { ... }
  }
}`;
}

export default buildAuditPrompt;
