/**
 * AUDIT PROMPT (version-controlled)
 * =================================
 * Discriminative audit prompt for Audit Mode. This is intentionally a DIFFERENT task from
 * the generative verification pipeline:
 *
 *   Verification asks:  "What IS the correct value?"        (generative)
 *   Audit asks:         "Is this CLAIMED value supported     (discriminative)
 *                        by the evidence — yes or no?"
 *
 * The discriminative framing is the whole point — it must NOT re-derive values from scratch
 * (that would just repeat whatever mistake the generator made). It judges a claim against the
 * supplied evidence and must cite the evidence behind every verdict so a human can check it.
 *
 * Output is strict JSON, per-field verdicts only. There is NO `corrections` block — a correction
 * only ever reaches Salesforce via a real verification run that later passes a re-audit.
 */

import { AuditFieldName, ClaimedValues } from '../types/audit.types';

const FIELD_GUIDE: Record<AuditFieldName, string> = {
  AI_Brand: 'Manufacturer/brand name (e.g. Samsung, Kohler, hansgrohe).',
  AI_Product_Category: 'The product category (e.g. Wall Oven, Showerheads & Accessories, Refrigerator).',
  AI_Type: 'The product type within the category (e.g. Single Oven, French Door, System).',
  AI_Style: 'The product style (e.g. Contemporary, Built-In, Transitional).',
  AI_Color: 'The product COLOR (e.g. Stainless Steel, White, Black, Chrome). A color is a visible appearance, not a surface treatment.',
  AI_Finish: 'The product FINISH/surface treatment (e.g. Polished, Brushed, Matte). May legitimately be empty if the source gives no finish.',
  AI_Product_Title: 'The generated marketing title. Judge whether it accurately reflects the product per the evidence (correct brand, key spec, type, color/finish, model number). If a component field below is wrong, the title is usually wrong too.',
};

/**
 * Build the full audit prompt.
 * @param claimed       the 7 AI values being judged
 * @param evidenceText  pre-assembled, human-readable evidence block (built by the service)
 */
export function buildAuditPrompt(claimed: ClaimedValues, evidenceText: string): string {
  const claimedBlock = (Object.keys(claimed) as AuditFieldName[])
    .map((k) => `- ${k}: ${claimed[k] === null || claimed[k] === '' ? '(empty)' : JSON.stringify(claimed[k])}\n    └ ${FIELD_GUIDE[k]}`)
    .join('\n');

  return `You are a meticulous product-data AUDITOR. Your job is NOT to generate product fields.
Your job is to JUDGE whether each already-claimed value below is supported by the EVIDENCE.

You are auditing AI-generated values that may be wrong. Be skeptical. Decide each field strictly
from the EVIDENCE provided — never from outside knowledge, never by guessing.

═══════════════════════════════════════════════════════════════════════
CLAIMED VALUES (these were generated by a previous AI run — judge them):
═══════════════════════════════════════════════════════════════════════
${claimedBlock}

═══════════════════════════════════════════════════════════════════════
EVIDENCE (the ONLY source of truth — descriptions, features, spec tables,
Ferguson / Web Retailer / Legacy fields from the product payload):
═══════════════════════════════════════════════════════════════════════
${evidenceText}

═══════════════════════════════════════════════════════════════════════
HOW TO JUDGE EACH FIELD
═══════════════════════════════════════════════════════════════════════
For every one of the 7 claimed fields, assign exactly one status:

• "MATCH"        — the EVIDENCE supports the claimed value. Provide a short verbatim "evidence"
                   snippet (quote the actual text/spec from the payload) that supports it.

• "MISMATCH"     — the EVIDENCE contradicts the claimed value. You MUST provide:
                     - "correct": the value the evidence actually supports
                     - "evidence": a verbatim snippet from the payload proving it
                     - "root_cause": a short hypothesis for WHY the previous AI got it wrong
                       (e.g. "Ferguson color empty; Web Retailer Color_Finish held 'Brushed', a
                       surface-treatment word, which was used as the color instead of the
                       'stainless steel' stated in the description").

• "UNSUPPORTED"  — the EVIDENCE neither confirms nor contradicts the claim (the sources are
                   silent on this field). Provide a "note" explaining what was missing.
                   DO NOT guess. UNSUPPORTED is not a failure — it means we can't tell.

CRITICAL RULES:
- Quote real text from the EVIDENCE in every "evidence" snippet. Do not paraphrase into something
  that isn't actually present. If you cannot find supporting text, the field is UNSUPPORTED, not MATCH.
- AI_Color vs AI_Finish: a COLOR is a visible appearance (Stainless Steel, White, Chrome). A FINISH
  is a surface treatment (Polished, Brushed, Matte). If the claimed color is actually a finish word,
  that is a MISMATCH.
- AI_Product_Title: a MISMATCH if it misstates brand, the key spec, type, color/finish, or model
  number relative to the evidence. If a component field is a MISMATCH, evaluate whether the title
  inherits that error.
- Judge ONLY the 7 fields listed. Do not invent new fields.

═══════════════════════════════════════════════════════════════════════
RESPONSE FORMAT — return ONLY this JSON object, no prose, no markdown fences:
═══════════════════════════════════════════════════════════════════════
{
  "fields": {
    "AI_Brand":            { "status": "MATCH|MISMATCH|UNSUPPORTED", "claimed": "<as given>", "correct": "<only if MISMATCH>", "evidence": "<verbatim snippet>", "root_cause": "<only if MISMATCH>", "note": "<only if UNSUPPORTED>" },
    "AI_Product_Category": { ... },
    "AI_Type":             { ... },
    "AI_Style":            { ... },
    "AI_Color":            { ... },
    "AI_Finish":           { ... },
    "AI_Product_Title":    { ... }
  }
}`;
}

export default buildAuditPrompt;
